dist: trusty
sudo: required

notifications:
  email: true

services:
  - docker

language: c

before_install:
  - git clone https://github.com/sancus-tee/sancus-main.git
  - cd sancus-main/docker && make build SANCUS_SECURITY=128

script:
  - docker run -t sancus-devel /bin/sh -c \
    "git clone https://github.com/sancus-tee/vulcan && cd vulcan &&
     git checkout $TRAVIS_BRANCH && LIBVULCAN=$LIBVULCAN TRAVIS=1 make $TARGET"
  - docker ps -a

env:
  - LIBVULCAN=vatican TARGET=sim
  - LIBVULCAN=leia    TARGET=sim
  - LIBVULCAN=vatican TARGET=mac
  - LIBVULCAN=leia    TARGET=mac
  - LIBVULCAN=vatican TARGET=demo
  - LIBVULCAN=leia    TARGET=demo
  - TARGET="sloc size"
